### ISSUE TITLE
Vanilla Genetics Expanded и Reinforced Mechanoids 2

### ISSUE THREAD

**Issue by younyokel** [OneCodeUnit/VanillaRussianExpanded#10]
Только эти не переведены. Добавьте пожалуйста в репозиторий.

**Comment by OneCodeUnit** [comment]
Reinforced Mechanoids 2 не имеет прямой связи с серией Vanilla Expanded. Более того, он не имеет связи (и общих строк) с первой версией, которую я переводил. На этот мод уже есть достаточно популярный перевод в мастерской. 

Vanilla Genetics Expanded это чудовищно большой в плане объёма переводимого текста мод, который очень быстро перевели другие люди. Ссылка на тот перевод есть в таблице.

Не вижу смысла переводить ни тот, ни другой с нуля. Если же авторы переводов тех модов захотят добавить их сюда, то я с радостью их поддержу.
